### ISSUE TITLE
Large DR APO scores for binary outcomes

### ISSUE THREAD

**Issue by jkortner** [MCKnaus/causalDML#4]
Thank you for the package! 

I'm using causalDML to estimate doubly robust APOs for a binary outcome variable and multiple treatments. 

```
ml = create_method("lasso", args=list(family = "binomial"))

cfm = prep_cf_mat(length(y), 4)
wm = prep_w_mat(w)

em = nuisance_e(list(ml), 
                wm, x , cfm, 
                cv=4, path=NULL, quiet=FALSE)

mm = nuisance_m(list(ml), 
                y, wm, x, cfm, 
                cv=4, path=NULL, quiet=FALSE, weights=FALSE)

apo <- APO_dml(y, mm, wm, em, norm=2, cf_mat=cfm)
```

The estimated dr APOs take values well outside of 0 and 1. 

```
summary(apo$gamma)
```

You discuss the problem of "implausibly large effect estimates that even could fall outside of the possible bounds of a given outcome variable" in your paper (ArXiv, p. 13), but I'm unsure how this can be used if my goal is to estimate dr APOs and not CATEs (as in your examples).

**Comment by MCKnaus** [comment]
There are two points here:
1. I guess that the apo$gammas outside 0/1 occur for the treatment the observation acutally receives. To see why look at the formula for $\hat{\Gamma} = \hat{\mu}(w,X_i) + D_i(w) (Y_i - \hat{\mu}(w,X_i))/ \hat{e}(X_i)$. The first part $\hat{\mu}(w,X_i)$ accepts the boundary if you use logistic Lasso as in your case. The second part is $(Y_i - \hat{\mu}(w,X_i))/ \hat{e}(X_i)$ if $i$ receives treatment $w$ and zero otherwise. This term easily can be larger than $1-\hat{\mu}(w,X_i)$ or smaller than $-\hat{\mu}(w,X_i)$ such that $\hat{\Gamma}$ falls outside 0/1. E.g. $\hat{\mu}= 0.5$, $\hat{e} = 0.5$, $D_i(w)=1$ and $Y_i=1$. Then $\hat{\Gamma} = 0.5 + (1-0.5)/0.5 = 1.5$ even without any problems of small pscores or alike. This is not concerning and absolutely expected. I hope this illustrates why using the single score $\hat{\Gamma}$ as an estimate for $E[Y_i(w)|X]$ is not very useful. Actually it is an unbiased estimator, but has basically infinite variance.
2. This is why we never look at individual $\hat{\Gamma}$ but smooth them using OLS/nonparametric/ML regressions as I describe in the paper. Then a normalization for conditional APOs would look like this: $\sum_i \alpha_i(x) \hat{\mu}(w,X_i)+ \left(\sum_i \lambda^w_i(x) \right)^{-1} \sum_i \lambda^w_i(x)  \tilde{Y_i}(w,X_i)$ instead of eq. 9 in the paper. This is currently not possible with the package, but would be nice to include in future versions.

I received offline similar questions and the main insight required is that the single score is not the estimator we want to use for individualized effects or potential outcomes. We want to use scores as pseudo-outcomes in standard regressions.

I hope this clarifies the problem, otherwise please let me know.

**Comment by MCKnaus** [comment]
See also our conversation on Twitter https://twitter.com/MC_Knaus/status/1563925226781548545
